# Generated by Django 5.2.5 on 2025-12-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietaryentry",
            name="item",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="dietaryentry",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exerciseentry",
            name="remarks",
            field=models.TextField(blank=True),
        ),
    ]
