# Generated by Django 4.2.27 on 2026-01-30 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Analysis"),
                            ("image", "Image Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="tracker_aiu_user_id_d819ff_idx",
                    ),
                    models.Index(
                        fields=["user", "request_type", "timestamp"],
                        name="tracker_aiu_user_id_06b4e9_idx",
                    ),
                ],
            },
        ),
    ]
