# Generated by Django 4.2.27 on 2026-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_userprofile_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary (little or no exercise)"),
                    ("light", "Lightly Active (1-3 days/week)"),
                    ("moderate", "Moderately Active (3-5 days/week)"),
                    ("active", "Very Active (6-7 days/week)"),
                    ("extra", "Extra Active (very active + physical job)"),
                ],
                help_text="Daily activity level",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="User's age in years", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calorie_profile_complete",
            field=models.BooleanField(
                default=False, help_text="Whether user has completed calorie goal setup"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_calorie_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Calculated daily calorie target", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fitness_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lose", "Lose Weight"),
                    ("gain", "Gain Weight"),
                    ("maintain", "Maintain Weight"),
                ],
                help_text="Weight management goal",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in centimeters",
                max_digits=5,
                null=True,
            ),
        ),
    ]
