# Generated by Django 4.2.27 on 2026-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_userprofile_activity_level_userprofile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietaryentry",
            name="coach_remark",
            field=models.TextField(blank=True),
        ),
    ]
