# Generated by Django 4.2.27 on 2026-01-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_dietaryentry_coach_remark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietaryentry",
            name="coach_remark",
        ),
    ]
