# Generated by Django 4.2.27 on 2026-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_userpoints_routine_completionrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completionrecord",
            name="points_earned",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="points_value",
        ),
        migrations.DeleteModel(
            name="UserPoints",
        ),
    ]
