# Generated by Django 4.2.27 on 2026-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_remove_completionrecord_points_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus"), ("pro", "Pro")],
                default="free",
                help_text="Current subscription tier",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tier_override",
            field=models.BooleanField(
                default=False,
                help_text="Admin manually granted this tier (bypasses payment)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tier_override_note",
            field=models.TextField(
                blank=True, help_text="Admin note for why tier was overridden"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ai_enabled",
            field=models.BooleanField(
                default=False, help_text="(Deprecated) Use subscription_tier instead"
            ),
        ),
    ]
