# Generated by Django 4.2.27 on 2026-03-22 12:01

from django.db import migrations


def migrate_tiers_forward(apps, schema_editor):
    """Migrate existing ai_enabled and special group users to tiers."""
    UserProfile = apps.get_model('tracker', 'UserProfile')
    Group = apps.get_model('auth', 'Group')

    # Users in 'special' group get Pro with override
    try:
        special_group = Group.objects.get(name='special')
        special_user_ids = special_group.user_set.values_list('id', flat=True)
        UserProfile.objects.filter(user_id__in=special_user_ids).update(
            subscription_tier='pro',
            tier_override=True,
            tier_override_note='Migrated from special group',
        )
    except Group.DoesNotExist:
        pass

    # Users with ai_enabled=True (but not already set to pro) get Plus
    UserProfile.objects.filter(
        ai_enabled=True,
        subscription_tier='free',
    ).update(
        subscription_tier='plus',
        tier_override=True,
        tier_override_note='Migrated from ai_enabled=True',
    )


def migrate_tiers_backward(apps, schema_editor):
    """Reverse: set ai_enabled based on tier."""
    UserProfile = apps.get_model('tracker', 'UserProfile')
    UserProfile.objects.filter(subscription_tier__in=['plus', 'pro']).update(ai_enabled=True)
    UserProfile.objects.filter(subscription_tier='free').update(ai_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_add_subscription_tiers"),
    ]

    operations = [
        migrations.RunPython(migrate_tiers_forward, migrate_tiers_backward),
    ]
